### ISSUE TITLE
Fauna Query methods need intellisense hints

### ISSUE THREAD

**Issue by csharpfritz** [fauna/faunadb-csharp#123]
Intellisense is not available for any objects in this package, and that makes discoverability of the features and interactions with the Fauna client very difficult for new developers

**Comment by ikourfaln** [comment]
indeed

**Comment by ikourfaln** [comment]
indeed

**Comment by n400** [comment]
Thanks for this suggestion. We agree and have it ticketed internally as DRV-534 for investigation.

**Comment by parkhomenko** [comment]
hi guys @csharpfritz @ikourfaln 
could you provide more details on this one?
I see that all the methods have xml comments, here is an example:
https://github.com/fauna/faunadb-csharp/blob/master/FaunaDB.Client/Query/Language.Basic.cs#L7-L12

**Comment by n400** [comment]
Closing this for now because we cannot reproduce it. Please let us know if we should reopen it.
