### ISSUE TITLE
Having null properties on Entities without using FaunaField attribute makes Decoder.Decode throw exception

### ISSUE THREAD

**Issue by overgaardmorten** [fauna/faunadb-csharp#48]
Save instance of User without filling out one of FirstName, LastName or Login makes Decoder.Decode<T> throw exception with message: Missing required property: PropertyName

```csharp 
public class User 
{
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Login Login { get; set; }
    }

    public class Login
    {
        public LoginTypeEnum LoginType { get; set; }

        public string Username { get; set; }
        public string PasswordHash { get; set; } 
        public string FacebookToken { get; set; }
    }
```

It would be nice if Decoder handles properties with null values simply by setting these to null when calling Decode.

**Comment by marrony** [comment]
@overgaardmorten I have a pr https://github.com/fauna/faunadb-csharp/pull/50 ready to review, when approved I should release a new version of the driver
