### ISSUE TITLE
Possibility for chaining style API?

### ISSUE THREAD

**Issue by Thaina** [fauna/faunadb-csharp#53]
After learning about faunadb API for sometimes I felt unfamiliar with the style of API

Such as

```C#
client.Query(
  Paginate(Match(Index("spells_by_element"), "fire")));
```

```C#
client.Query(
  Do(
    Create(
      Ref(Class("magical_creatures"), 1),
      Obj("data", Obj("name", "Hen Wen"))),
    Get(Ref(Class("magical_creatures"), 1))));
```

I felt that some functions that require `Expr` as parameter should be extension method. And so we could write it like this

```C#
client.Query(Index("spells_by_element").Match("fire").Paginate());
```

```C#
client.Query(Do(Class("magical_creatures").Ref(1).Create(Obj("data", Obj("name", "Hen Wen")))
     ,Class("magical_creatures").Ref(1).Get()));

/// or

client.Query(Class("magical_creatures").Ref(1).Create(Obj("data", Obj("name", "Hen Wen")))
    .Then(Class("magical_creatures").Ref(1).Get()));
```

Could we have a sub namespace for this style api? (FaunaDB.LINQ maybe?)

**Comment by eaceaser** [comment]
Thanks for requesting these improvements!

We're actually in the process of taking a pass on improving our language-specific APIs to hopefully make things feel a bit more natural - as you discovered, the function-composition nature of our underlying API leaks out in ways that feel unfamiliar.

I'll keep this ticket open so we can update you when we have something new to play with.

**Comment by n400** [comment]
Closing this issue to track internally as DRV-537. Will open a Discussion once we have something ready for alpha testing
