### ISSUE TITLE
HttpClient & TCP Connections

### ISSUE THREAD

**Issue by mayoatte** [fauna/faunadb-csharp#73]
Hey folks,

Just came across FaunaDb. While checking out this driver I noticed that it seems to create a new HttpClient every time.

A lot of the serverless platforms (FaaS ones like Lambda and Azure Functions) have [limits on the number of connections](https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections) that can be created inside a function and inappropriate usage HttpClient is frequently the cause of many errors.

The old way to fix this was to use a static http client but that has problems as well. The newer way is to use an [HttpClientFactory](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) which does a much better job of managing connections.

Anyways. Just wanted to bring that up. The serverless tier of FaunaDb is what caught my eye and this is a frequent gotcha for those scenarios.

**Comment by kcrandall** [comment]
evbruno this can be closed now
