### ISSUE TITLE
Feature Request: Encoder/Decoder Uri and similar types as a string

### ISSUE THREAD

**Issue by kcrandall** [fauna/faunadb-csharp#96]
would be nice if you could have a Uri be encoded as a string into faunadb. this can be accomplished similar to the [FaunaDate] and [FaunaTime] attributes. You can have a [FaunaString] that encodes the object by calling the .ToString() and the decoder calls a constructor with a single parameter, string.

**Comment by evbruno** [comment]
issue merged on PR #99
